<?php $_itemhash = $this->getOrderedStats() ?>
<?php $_totalcost = 0 ?>
<div class="grid" style="padding-bottom: 0;">
    <table class="border" cellpadding="0" cellspacing="0">
        <colgroup>
            <col width="10%">
            <col>
            <col>
        </colgroup>
        <?php foreach ($_itemhash as $item ): ?>
        <thead>
            <tr class="itemheader">
                <th style="text-align: right;border-bottom:1px solid #fff;padding-top: 5px;background-color: #ddd;padding-right:10px;"><?php echo $item['qty']; ?></th>
                <th style="border-bottom:1px solid #fff;padding-top: 5px;background-color: #ddd;"><?php echo $item['name']; ?></th>
                <th style="border-bottom:1px solid #fff;padding-top: 5px;background-color: #ddd;"><?php if($item['volume'] >0): ?><?php echo $item['volume']; ?> <?php echo $item['unit']; ?><?php endif;?></th>
                <th style="border-bottom:1px solid #fff;padding-top: 5px;background-color: #ddd;"><?php if($item['cost'] >0): ?><?php echo floor( $item['cost'] ) . ' ' . Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?><?php endif;?></th>
            </tr>
        </thead>
        <?php $_totalcost += $item['cost']; ?>
        <?php if(count($item['options'])): ?>
            <tbody>
            <?php foreach ($item['options'] as $option): ?>
                <tr class="optionheader">
                    <td style="padding-right: 10px;"></td>
                    <td style="text-transform: uppercase;border-bottom:1px solid #999;padding-top: 8px;" colspan="3"><?php echo $option['label']; ?></td>
                </tr>
                <?php foreach ($option['values'] as $value): ?>
                <tr class="optionstats">
                    <td style="text-align: right;padding-right: 10px;"><?php echo $value['qty']; ?></td>
                    <td><?php echo $value['name']; ?></td>
                    <td><?php echo $value['volume']; ?> <?php echo $value['volumeunit']; ?></td>
                    <td><?php echo floor($value['cost']) . ' ' . Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?></td>
                </tr>
                    <?php $_totalcost += $value['cost']; ?>
                <?php endforeach; ?>
            <?php endforeach; ?>
            </tbody>
        <?php endif; ?>
        <?php endforeach; ?>
        <?php if( $_totalcost > 0 ): ?>
        <tfoot>
            <tr>
                <td colspan="3"></td>
                <td ><?php echo floor($_totalcost) . ' ' . Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?></td>
            </tr>
        </tfoot>
        <?php endif; ?>
    </table>
</div>
