<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard"><?php echo $this->__('Dashboard') ?></h3></td>
        </tr>
    </table>
</div>
<div class="dashboard-container">
    <div class="entry-edit" style="border:1px solid #ccc;">
        <div class="entry-edit-head"><h4><?php echo $this->__('Bestilt') ?></h4></div>
        <fieldset style="margin-bottom: 0;">
            <form id="updatestats" method="post" action="<?php echo Mage::helper('adminhtml')->getUrl('*/*/orderedstats'); ?>">
                <?php echo $this->getForm()->getHtml(); ?>
                <?php echo $this->getStatsButtonHtml(); ?>
            </form>
        </fieldset>
        <div id="digidennis-dashboard-orderedstats"><?php echo $this->getChildHtml('dashboard.orderedstats'); ?></div>
    </div>
    <script>
        function updatestats(){
            var form = $('updatestats');
            new Ajax.Request( form.action, {
                method: 'POST',
                parameters:form.serialize(),
                onComplete: function(transport) {
                    $('digidennis-dashboard-orderedstats').update(transport.responseText);
                }
            });
        }
    </script>
</div>