<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard"><?php echo $this->__('Dashboard') ?></h3></td>
        </tr>
    </table>
</div>
<div class="dashboard-container">
    <table cellspacing="25" width="100%">
        <tr>
            <td><?php echo $this->getChildHtml('sales') ?>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo $this->__('Klar til bestilling') ?></h4></div>
                    <fieldset>
                        <p><b>Antal: </b><?php echo $this->getReadyToProcess(); ?><?php echo $this->getButtonHtml( 'Print', '*/*/shipmentmakeprint', 'go right'); ?></p>
                    </fieldset>
                </div>
            </td>
            <td>
                <div class="entry-edit" style="border:1px solid #ccc;">
                    <div class="entry-edit-head"><h4><?php echo $this->__('Bestilt') ?></h4></div>
                    <?php echo $this->getChildHtml('dashboard.orderedstats'); ?>
                </div>
                <!--script>
                    new Ajax.Updater('dashboard-orderdstats', '<?php echo Mage::helper('adminhtml')->getUrl('*/*/orderedstats'); ?>' );
                </script-->
            </td>
        </tr>
    </table>
</div>